### ISSUE TITLE
Which bugtracker?

### ISSUE THREAD

**Issue by cxw42** [salva/p5-XML-FromPerl#1]
@salva Thanks for this module!  I would like to submit some enhancements.  May I use the GitHub issue/PR interface, or would you prefer to use RT for discussion?  Please let me know either way.  Thanks!

-CXW

**Comment by salva** [comment]
GitHub, please!

    On Saturday, June 8, 2019, 3:56:21 PM GMT+2, Chris White <notifications@github.com> wrote:  
 
 
@salva Thanks for this module! I would like to submit some enhancements. May I use the GitHub issue/PR interface, or would you prefer to use RT for discussion? Please let me know either way. Thanks!

-CXW
